apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
resources:
  - ../../apps/model-api/base
  - ../../apps/vendor-manager/base
labels:
  - includeSelectors: false
    pairs:
      env: dev
patches:
  - path: model-api-patches.yaml
    target: { kind: Ingress, name: model-api }
  - path: vendor-manager-ingress-patches.yaml
    target: { kind: Ingress, name: vendor-manager }
  - path: vendor-manager-configmap-patches.yaml
    target: { kind: ConfigMap, name: vendor-manager-config }
  - path: vendor-manager-postgres-patches.yaml
    target: { kind: StatefulSet, name: vendor-manager-db }