- op: replace
  path: /spec/rules/0/host
  value: dev.pipelines.durczok.ovh
- op: replace
  path: /spec/tls/0/hosts/0
  value: dev.pipelines.durczok.ovh
- op: replace
  path: /spec/tls/0/secretName
  value: pipelines-webserver-tls-dev
- op: replace
  path: /metadata/annotations/traefik.ingress.kubernetes.io~1router.middlewares
  value: dev-pipelines-auth@kubernetescrd
