- op: replace
  path: /spec/rules/0/host
  value: dev.files.pipelines.durczok.ovh
- op: replace
  path: /spec/tls/0/hosts/0
  value: dev.files.pipelines.durczok.ovh
- op: replace
  path: /spec/tls/0/secretName
  value: pipelines-filebrowser-tls-dev
