apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chains
  namespace: dev
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik
  tls:
    - hosts: [chains.durczok.ovh]
      secretName: chains-tls
  rules:
    - host: chains.durczok.ovh
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: chains
                port:
                  number: 80
